spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=never

spring.h2.console.enabled=false

jwt.secret=${JWT_SECRET}
jwt.access-token-validity-in-seconds=${JWT_ACCESS_TOKEN_VALIDITY_IN_SECONDS:3600}

kakao.client-id=${KAKAO_CLIENT_ID:}
kakao.client-secret=${KAKAO_CLIENT_SECRET:}
kakao.redirect-uri=${KAKAO_REDIRECT_URI:}
